CHANGELOG.md
lib/procore/auth/access_token_credentials.rb
lib/procore/auth/client_credentials.rb
test/procore/auth/access_token_credentials_test.rb
test/procore/auth/client_credentials_test.rb

This allows users to only have to worry about our gem's errors. This resolves #5.

feat: Wrap AccessTokenCredentials in our own errors

---

CHANGELOG.md
README.md
lib/procore/client.rb
lib/procore/requestable.rb
test/procore/requestable_test.rb

This branch adds the `Client#put` method to support HTTP PUT requests.

feat: Add HTTP PUT support

---

CHANGELOG.md
lib/procore/auth/stores/redis.rb

If a user deletes a token, then attempts to retreive that same token,
the SDK will raise an error because we are attempting to call #empty on
nil.
This changes the #get to an #exists check, and actually removes the key
from redis instead of setting it to nil.

fix: Redis guard clause

---

CHANGELOG.md
lib/procore/requestable.rb

This allows clients to debug and handle API responses that are caused
from malformed requests

feat: Add 400 response code as a bad request error

---

CHANGELOG.md
lib/procore/requestable.rb
lib/procore/response.rb
test/procore/response_test.rb

After we moved to RestClient it became impossible to access the request
body after the request had been made. This feature allows us to maintain
the previous requirement for debugging.

feat: Save request body for debugging

---

CHANGELOG.md
README.md
lib/procore/client.rb
lib/procore/errors.rb
lib/procore/requestable.rb
test/procore/auth/client_credentials_test.rb
test/procore/client_test.rb

Rescue Procore::OauthError in requestable to help alleviate concurrency issue.
1. Several threads all attempt to refresh a token at once.
2. First one succeeds, and replaces the token in the store
3. Second thread attempts to refresh, errors and raises Procore::OAuth
4. Retries request, this time getting the new credentials set by the first thread.

Rescue Procore::OAuthError

---

CHANGELOG.md
lib/procore/requestable.rb

rescue Errno::ECONNRESET errors so they can be retried.

rescue Errno::ECONNRESET errors

---

CHANGELOG.md
lib/procore/requestable.rb
lib/procore/version.rb

- This prevents getting bugs from using `client.get("/example")` instead of `client.get("example")`
- The former would have resulted in `http://example.com//example` throwing an error, while the later would have worked. Now both work, preventing a common bug. IAM just encountered this one.

use file join for uris to prevent double slash

---

.travis.yml
lib/procore/auth/client_credentials.rb
procore.gemspec

Lock the SQLite version to 1.3.x, as Rails 5.2 has a lock on that particular
version. Added Ruby 2.6 to the travis testing matrix as well, and added
handling for another potential URI error.

fix: On Ruby 2.6 + Rails 5.2

---

CHANGELOG.md
lib/procore/client.rb
lib/procore/requestable.rb
lib/procore/response.rb
lib/procore/version.rb
test/procore/requestable_test.rb

As we move to our 'rest' endpoints, we need to remove the vapid prefix for requests.
This is backwards compatible with what the client was doing. It now supports 'rest' api calls as well now.

remove vapid prefix for rest endpoint requests

---

CHANGELOG.md
README.md
lib/procore/configuration.rb
lib/procore/defaults.rb
lib/procore/requestable.rb
test/procore/requestable_test.rb

Sync actions enable batch creation or updates for certain supported
resources in the Procore API.
See https://developers.procore.com/documentation/using-sync-actions
for documentation on how to use sync actions.
Related to #33.
---
@phuminhphan apologies, my thoughts didn't come across clearly in #33. What I was getting at is that `sync` is definitely a primitive worth exposing, it just needs to behave like the other methods on [Client do](https://github.com/procore/ruby-sdk#making-requests). 
```ruby
client.sync(
"projects/sync",
body: {
updates: [
{ id: 1, name: "Update 1" },
{ id: 2, name: "Update 2" },
{ id: 3, name: "Update 3" },
...
...
{ id: 5055, name: "Update 5055" },
]
},
options: { batch_size: 500, company_id: 1 },
)
```
By being implemented in`requestable`, the correct API …

feat: Expose #sync

---

.rubocop.yml
CHANGELOG.md
README.md
lib/procore/client.rb
lib/procore/configuration.rb
lib/procore/defaults.rb
lib/procore/requestable.rb
lib/procore/response.rb
procore.gemspec
test/procore/client_test.rb
test/procore/requestable_test.rb
test/procore/response_test.rb
test/test_helper.rb

Ticket: [ZL-751](https://procoretech.atlassian.net/browse/ZL-751)
This PR changes how the SDK handles API versions, to support easy migration from the legacy API Vapid to the new versioned API Rest. Read more about the Rest versioned API in our [Confluence pages](https://procoretech.atlassian.net/wiki/spaces/DEV/pages/1360265934/Procore+Rest+API).
An optional `default_version` can now be set during configuration, and should be either `v1.0` (recommended) or `vapid` (legacy). If no default version is provided, it is automatically set to `v1.0`.
```ruby
Procore.configure do |config|
...
config.default_version = "v1.0"
...
end
```
The API version can also be specified at the time of the request.
| Example | Requested URL |
| --- | --- |
| `client.get("me")` | …

[ZL-751] Support Rest API migration

---

CHANGELOG.md
README.md
lib/procore/auth/access_token_credentials.rb
lib/procore/client.rb
lib/procore/requestable.rb
lib/procore/version.rb
test/procore/client_test.rb
test/support/auth_stubs.rb

Ticket: [ZL-874](https://procoretech.atlassian.net/browse/ZL-874)
This PR adds functionality to allow clients to manually refresh and revoke their token.
Pretty simple:
```ruby
client = Procore::Client.new( ... )
client.refresh
client.revoke # client will refresh token on its next request
```

[ZL-874] Manually refresh and revoke tokens

---

.rubocop.yml
CHANGELOG.md
README.md
lib/procore/defaults.rb

Fixes https://github.com/procore/ruby-sdk/issues/41
The default host should be `api.procore.com` not `app.procore.com`.

Change default host to api.procore.com

---

README.md

ZL-970
https://github.com/procore/ruby-sdk/issues/40
Updated the README to include information about setting `company_id` in `options`. Provide link to our documentation as to why its required.

[ZL-970] Update README to include company_id option information

---

CHANGELOG.md
lib/procore/auth/stores/redis.rb

This commit removes the following warning when using the gem
> `Redis#exists(key)` will return an Integer in redis-rb 4.3. `exists?`
> returns a boolean, you should use it instead. To opt-in to the new behavior
> now you can set Redis.exists_returns_integer =  true. To disable this message
> and keep the current (boolean) behaviour of 'exists' you can set
> `Redis.exists_returns_integer = false`, but this option will be removed in 5.0.

Remove Redis.exists warning

---

CHANGELOG.md
lib/procore/requestable.rb
test/procore/requestable_test.rb

https://procoretech.atlassian.net/browse/ZL-1055
Break up `Procore-Sdk-Version` to send language in `Procore-Sdk-Language`

Break up sdk header into language and version

---

CHANGELOG.md
lib/procore/auth/access_token_credentials.rb
lib/procore/auth/client_credentials.rb
lib/procore/client.rb

This PR contains two bug fixes for the Procore Ruby SDK:
When a token was automatically refreshed, the first request would fail. The token is now updated in memory so this will not occur.
Resolves issue: https://github.com/procore/ruby-sdk/issues/51
The path fragment `/oauth/token` was incorrectly inserted into the `host` URL when the Oauth2 client is initialized. Older versions of Oauth2 apparently stripped this out, but not the recent version I was using.

[AGX-814] Fix bugs with token refresh and Oauth2 URL

---

test/test_helper.rb

SimpleCov was showing zero coverage for the repository, even though we had tests. This PR fixes the test_helper.rb, simplecov now generates accurate coverage that can be pushed to sonarqube.
SimpleCov needs to be [launched before any application code](https://github.com/simplecov-ruby/simplecov#getting-started) in test_helper.rb for it to work. Else it generates zero coverage. 
Completed testing locally, Coverage numbers are being generated now.

SimpleCov report fix

---

CHANGELOG.md
README.md
lib/procore/client.rb
lib/procore/configuration.rb
lib/procore/defaults.rb
test/procore/client_test.rb
test/support/auth_stubs.rb
test/test_helper.rb

This PR introduces `:login_host` configuration value used to set up OAuth2::Client. 
The work is done to migrate SDK users from calling `https://api.procore.com/oauth/token` (which is basically a proxcy call in the monolith) to calling the login service directly via `https://login.procore.com/oauth/token`.     
Please see this [Slack thread](https://procoretech.slack.com/archives/C0HMLDAKY/p1703016580126819) for additional details.

add login_host option

---

CHANGELOG.md
lib/procore/requestable.rb
lib/procore/version.rb
test/procore/requestable_test.rb

This PR fixes a bug with the retry logic in `with_response_handling` resulting in performing one more retry than expected .

Fix retry logic

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/release.yaml
.github/workflows/test.yaml
README.md

chore: remove references to master branch

---

.github/CODEOWNERS
.github/workflows/release.yaml

Move version file change check to its own job
allows us to simplify conditional checks to one
in other steps since they will be under their own
job now
Checklist:

chore: simplify release GitHub Action

---

.github/workflows/test.yaml
SECURITY.md
procore.gemspec

chore: drop ruby 2.7 support

---

.github/workflows/release.yaml

Closes https://github.com/procore-oss/ruby-sdk/pull/78
due to recent security concerns, changing this to sha most likely temporary as this will be replaced with a bash script or alternative action due to outstanding concerns on this action
Checklist:

fix: update tj-actions/changed-files to SHA instead of tag
